#%RAML 1.0
title: ProcessDemo Logistics Portal EXP API

types:
  Order:
    properties:
      orderId: string
      customerId: string
      orderRef: string
      orderAcceptedDateTime: datetime
      orderDescription: string
      orderTotalValue: number
  Orders:
    properties:
      resultCount: integer
      orders: Order[]
  OrderShippingData:
    properties:
      shippedDateTime: datetime
      shippingTrackingId: string
      shippingPartner: string
  PostalAddress:
    properties:
      addressStreet1: string
      addressStreet2: string
      addressStreet3: string
      townOrCity: string
      countyRegionOrState: string
      postcodeOrZip: string
      country: string

/orders:
  get:
    queryParameters:
      orderBy:
        type: string
        enum: [value, age]
    responses:
      200:
        body:
          application/json:
            type: Orders

  /{orderId}/shippingData:
    post:
      body:
        application/json:
          type: OrderShippingData
      responses:
        201:
        403:
          description: 403 Forbidden will be returned if shippingData is submtted for an order which has already been fulfilled.
          body:
            application/json:
              example: |
                {"message":"Shipping Data cannot be accepted for order {orderId}, as the order hs already been fulfilled."}
/customers/{customerId}:
  get:
    responses:
      200:
        body:
          application/json:
