#%RAML 1.0 NamedExample
value:
  {
      'orderId': "1",
      "customerId": "cid01",
      "orderRef": "001",
      "orderAcceptedDateTime": "2018-05-30T09:00:00",
      "orderDescription": "example order description",
      "orderTotalValue": 20,
      "status": "active"
}