#%RAML 1.0
title: ProcessDemo Accounts Portal EXP API

types:
  Order:
    properties:
      orderId: string
      customerId: string
      orderRef: string
      orderAcceptedDateTime: datetime
      orderDescription: string
      orderTotalValue: number
  Orders:
    properties:
      resultCount: integer
      orders: Order[]
  OrderInvoiceData:
    properties:
      invoicedDateTime: datetime
      invoiceAmount: number
      invoiceId: string
  OrderPaymentData:
    properties:
      paymentDateTime: datetime
      paymentAmount: number
      paymentExternalReference: string
      paymentId: string

/orders:
  get:
    queryParameters:
      orderBy:
        type: string
        enum: [value, age]
    responses:
      200:
        body:
          application/json:
            type: Orders

  /{orderId}/invoices:
    post:
      body:
        application/json:
          type: OrderInvoiceData
      responses:
        201:
