#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/b42ca970-cac7-453f-966e-eedd5baf50db # 
version: v1
title: Customer Portal EXP API

types:
  CustomerOrder:
    properties:
      customerId:
        type: string
        required: true
        example: "F1123581321"
      orderReference:
        type: string
        required: true
        example: "100W20180913"
      orderDetail:
        properties:
          totalOrderValue:
            type: number
            required: true
            example: 100.00
          orderDescription:
            type: string
            required: true
            example: "100 widgets @ $1 each."

      
  CustomerOrderResponse:
    properties: 
      orderId: string
      orderAcceptedDateTime: string
      

/orders:
  post:
    body:
      application/json:
        type: CustomerOrder
    responses:
      202:
        body:
          application/json:
            type: CustomerOrderResponse
            example: {"orderId":"A00120180913101112", "orderAcceptedDateTime":"20180913T101112Z"}
