#%RAML 1.0
title: ProcessDemo Customer SYS API

types:
  ContactPreferences:
    properties:
      preferredMedium:
        description: One of - email, homePhone, mobilePhone, workPhone
        type: string
      email: string
      homePhone: string
      mobilePhone: string
      workPhone: string
  Address:
    properties:
      addressStreet1: string
      addressStreet2: string
      addressStreet3: string
      townOrCity: string
      countyRegionOrState: string
      postcodeOrZip: string
      country: string
  Customer:
    properties:
      name:
        type: string
        required: true
      customerId:
        type: string
        required: true
      customerCreditLimit: number
      postalAddress: Address
      billingAddress: Address
      contactPreferences: ContactPreferences

/customers/{customerId}:
  get:
    queryParameters:
      view:
        description: One of - full, summary, logistics, invoicing, billing
        type: string
    responses:
      200:
        body:
          application/json:
            type: Customer
